### ISSUE TITLE
Hello..

### ISSUE THREAD

**Issue by glennkreisel** [leo/buffer#3]
I have modified your BUFFER php code to handle multiuser access to the cache index file.  I was having issues with many APACHE requests all trying to cache to the same cache file you had setup.  I added some locking so requests don't overwrite each other.    You can see the locking and it works great now.  

[buffer.php.zip](https://github.com/leo/buffer/files/246110/buffer.php.zip)

**Comment by leo** [comment]
Thank you for your contribution. :blush:

However, I'm not able to accept .zip files. If you want to contribute code to a project on GitHub, you need to [fork](https://help.github.com/articles/fork-a-repo/) the repo to your own GitHub account and then [clone](https://help.github.com/articles/cloning-a-repository/) the fork to your local device. After that, you can open a Pull Request.
